namespace WAD.NET.Definitions.Classic.Map
{
    public enum ThingType
    {
        PLAYER = 0,

        TROOPER = 1,
        SHOTGUY = 2,
        ARCHVILE = 3,
        REVENANT = 5,
        MANCUBUS = 8,
        CHAINGUY = 10,
        IMP = 11,
        DEMON = 12,
        SPECTRE = 13,
        CACODEMON = 14,
        BARONOFHELL = 15,
        HELLKNIGHT = 17,
        LOSTSOUL = 18,
        SPIDERMASTERMIND = 19,
        ARACHNOTRON = 20,
        CYBERDEMON = 21,
        PAINELEMENTAL = 22,
        WOLFSS = 23,
        KEEN = 24,
        BOSSBRAIN = 25,
        BOSSSPIT = 26,
        BOSSTARGET = 27,

        REVENANTMISL = 6,
        IMPSHOT = 31,
        CACOSHOT = 32,
        FLYINGROCKET = 33,
        FLYINGPLASMA = 34,
        FLYINGBFG = 35,
        ARACHPLAZ = 36,
        MANCUBUSSHOT = 9,
        BARONSHOT = 16,
        SPAWNSHOT = 28,

        PUFF = 37,
        BLOOD = 38,
        TFOG = 39,
        IFOG = 40,
        TELEPORTMAN = 41,
        EXTRABFG = 42,
        VILEFIRE = 4,
        SMOKE = 7,
        SPAWNFIRE = 29,
        PARTICLE = 145,

        GREENARMOR = 43,
        BLUEARMOR = 44,
        HEALTHPOTION = 45,
        ARMORHELMET = 46,
        STIMPACK = 53,
        MEDIKIT = 54,

        BLUEKEYCARD = 47,
        REDKEYCARD = 48,
        YELLOWKEYCARD = 49,
        YELLOWSKULLKEY = 50,
        REDSKULLKEY = 51,
        BLUESKULLKEY = 52,

        SUPERCHARGE = 55,
        INVULNERABILITY = 56,
        BESERKPACK = 57,
        INVISIBILITY = 58,
        RADSUIT = 59,
        AUTOMAP = 60,
        LITEAMP = 61,
        MEGASPHERE = 62,

        CLIP = 63,
        BULLETBOX = 64,
        ROCKET = 65,
        ROCKETBOX = 66,
        ECELL = 67,
        ECELLPACK = 68,
        SHELLS = 69,
        SHELLBOX = 70,
        BACKPACK = 71,

        BFG = 72,
        CHAINGUN = 73,
        CHAINSAW = 74,
        RLAUNCHER = 75,
        PLASMAGUN = 76,
        SHOTGUN = 77,
        SUPERSHOTGUN = 78,

        BARREL = 30,
        TALLTECHLAMP = 79,
        SHORTTECHLAMP = 80,
        FLOORLAMP = 81,
        TALLGRNPILLAR = 82,
        SHRTGRNPILLAR = 83,
        TALLREDPILLAR = 84,
        SHRTREDPILLAR = 85,
        SKULLCOLUMN = 86,
        HEARTCOLUMN = 87,
        EVILEYE = 88,
        SKULLROCK = 89,
        GRAYTREE = 90,
        TALLBLUFIRESTICK = 91,
        TALLGRNFIRESTICK = 92,
        TALLREDFIRESTICK = 93,
        SHRTBLUFIRESTICK = 94,
        SHRTGRNFIRESTICK = 95,
        SHRTREDFIRESTICK = 96,
        STALAGMITE = 97,
        TALLTECHPILLAR = 98,
        CANDLE = 99,
        CANDELABRA = 100,
        TREE = 126,
        BURNINGBARREL = 127,

        TWITCHCORPSE1 = 101,
        TWITCHCORPSE2 = 110,
        HANGINGMAN1 = 102,
        HANGINGMAN2 = 103,
        HANGINGMAN3 = 104,
        HANGINGMAN4 = 105,
        HANGINGMAN5 = 106,
        HANGINGMAN6 = 107,
        HANGINGMAN7 = 108,
        HANGINGMAN8 = 109,
        HANGINGMAN9 = 128,
        HANGINGMAN10 = 129,
        HANGINGMAN11 = 130,
        HANGINGMAN12 = 131,
        HANGINGMAN13 = 132,
        HANGINGMAN14 = 133,

        DEADCACO = 111,
        DEADPLAYER = 112,
        DEADTROOPER = 113,
        DEADDEMON = 114,
        DEADLOSTSOUL = 115,
        DEADIMP = 116,
        DEADSERGEANT = 117,
        SLOP = 118,
        SLOP2 = 119,
        SKULLPOLE1 = 120,
        SKULLPOLE2 = 122,
        BLOODPOOL1 = 121,
        SKULLPILE = 123,
        BLOODPOOL2 = 134,
        BLOODPOOL3 = 135,
        BLOODPOOL4 = 136,

        DEADCORPSE1 = 124,
        TWITCHCORPSE3 = 125,

        PUSH = 137,
        PULL = 138,
        DOGS = 139,
        MF_SPECIAL = 0,
        MF_SOLID = 1,
        MF_SHOOTABLE = 2,
        MF_NOSECTOR = 3,
        MF_NOBLOCKMAP = 4,

        MF_AMBUSH = 5,
        MF_JUSTHIT = 6,
        MF_JUSTATTACKED = 7,
        MF_SPAWNCEILING = 8,
        MF_NOGRAVITY = 9,

        MF_DROPOFF = 10,
        MF_PICKUP = 11,
        MF_NOCLIP = 12,
        MF_SLIDE = 13,
        MF_FLOAT = 14,
        MF_TELEPORT = 15,
        MF_MISSILE = 16,
        MF_DROPPED = 17,
        MF_SHADOW = 18,
        MF_NOBLOOD = 19,
        MF_CORPSE = 20,
        MF_INFLOAT = 21,

        MF_COUNTKILL = 22,
        MF_COUNTITEM = 23,

        MF_SKULLFLY = 24,

        MF_NOTDMATCH = 25,

        MF_TRANSLATION = 26,


        PLASMA_L = 1,
        PLASMAEXP_L = 2,
        ROCKET_L = 3,
        ROCKETEXP_L = 4,
        BFG_L = 5,
        BFGEXP_L = 6,
        BLUETALL_L = 7,
        GREENTALL_L = 8,
        REDTALL_L = 9,
        BLUESMALL_L = 10,
        GREENSMALL_L = 11,
        REDSMALL_L = 12,
        TECHLAMP_L = 13,
        TECHLAMP2_L = 14,
        COLUMN_L = 15,
        CANDLE_L = 16,
        CANDLEABRE_L = 17,
        REDBALL_L = 18,
        GREENBALL_L = 19,
        ROCKET2_L = 20,

        CORONA_TYPE = 0,
        CORONA_OFFX = 1,
        CORONA_OFFY = 2,
        CORONA_COLOR = 3,
        CORONA_SIZE = 4,

        LIGHT_COLOR = 5,
        LIGHT_RADIUS = 6,
        UNDEFINED_SPR = 0,
        CORONA_SPR = 1,
        DYNLIGHT_SPR = 2,
        LIGHT_SPR = 3,
        ROCKET_SPR = 19
    }
}
